import prisma from "@/libs/prisma";

export async function seedCategoria(establesimiento: string, usuario: string) {
  const count = await prisma.categoria.count({
    where: { establesimiento },
  });

  if (count > 0) return;

  await prisma.categoria.createMany({
    data: [
      {
        nombre: "Vaca",
        sexo: "Hembra",
        edad: "Adulto",
        promedioKilos: 350,
        precioVentaCabeza: 4000000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "Vaquilla",
        sexo: "Hembra",
        edad: "Adulto",
        promedioKilos: 280,
        precioVentaCabeza: 2500000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "Toro",
        sexo: "Macho",
        edad: "Adulto",
        promedioKilos: 500,
        precioVentaCabeza: 6000000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "Novillo",
        sexo: "Macho",
        edad: "Adulto",
        promedioKilos: 400,
        precioVentaCabeza: 5000000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "Desmamante Macho",
        sexo: "Macho",
        edad: "Joven",
        promedioKilos: 160,
        precioVentaCabeza: 2200000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "Desmamante Hembra",
        sexo: "Hembra",
        edad: "Joven",
        promedioKilos: 140,
        precioVentaCabeza: 1900000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "Ternero Macho",
        sexo: "Macho",
        edad: "RecienNacido",
        promedioKilos: 40,
        precioVentaCabeza: 800000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "Ternero Hembra",
        sexo: "Hembra",
        edad: "RecienNacido",
        promedioKilos: 30,
        precioVentaCabeza: 600000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
      {
        nombre: "BUEY",
        sexo: "Macho",
        edad: "Adulto",
        promedioKilos: 550,
        precioVentaCabeza: 6000000,
        precioVentaKilo: 40000,
        precioCostoCabeza: 3000000,
        precioCostoKilo: 30000,
        establesimiento,
        usuario,
      },
    ],
  });

  console.log("✅ Categoria sembrado");
}
